#include"communication/data/delete_data_c2s.h"
#include"communication/data/new_client_id_c2s.h"
#include"communication/data/new_client_id_s2c.h"
#include"communication/data/query_c2s.h"
#include"communication/data/result_c2s.h"
#include"communication/data/result_s2c.h"
#include"communication/data/update_const_data_c2s.h"
#include"communication/data/update_scheme_c2s.h"
